on: [push, pull_request]
jobs:
  test-and-build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request' }}
      - name: Checkout Pull Request Code
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Rust
        run: rustup update stable
      - name: Install llvm-cov
        run: cargo +stable install cargo-llvm-cov
      - name: Build
        run: cargo +stable build --verbose
      - name: Test
        run: cargo +stable test --verbose
      - name: Check Coverage
        run: cargo +stable llvm-cov --lcov --output-path coverage.info
      - name: Upload Coverage
        if: ${{ matrix.os != 'windows-2022' }}
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key rust --value-file coverage.info
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      - name: Upload Coverage (Windows)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          curl https://deepsource.io/cli | sh
          .\bin\deepsource report --analyzer test-coverage --key rust --value-file coverage.info
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
